name: Build and deploy Node.js app to Azure Web App - planning-poker-100

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies for React app
        run: |
          npm install

      - name: Build React app
        run: |
          npm run build

      - name: Install dependencies for Node.js server
        run: |
          cd server
          npm install

      - name: Build Node.js server
        run: |
          cd server
          npm run build --if-present

      - name: Prepare artifact for deployment
        run: |
          mkdir -p deploy/client
          cp -r build deploy/client
          cp -r server deploy/server
          cp server/package.json deploy/server
          cp server/package-lock.json deploy/server
          cd deploy
          zip -r release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: deploy/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip deploy/release.zip -d deploy

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_00818A86B99A47B2BC2170B20CB46650 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE0D37E0CFCC482F8BDECFF66D8CF289 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F3EEC284F0D484AA6B8EA2ACA562983 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'planning-poker-100'
          slot-name: 'Production'
          package: ./deploy/release.zip
