name: Build and deploy Node.js app to Azure Web App - planning-poker-100

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies for React app
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Install dependencies for Node.js server
        run: |
          cd server
          npm install

      - name: Prepare artifact for deployment
        run: |
          mkdir -p deploy/client
          mkdir -p deploy/server
          cp -r build/* deploy/client/
          cp -r server/* deploy/server/
          cp server/package.json deploy/server/
          cp server/package-lock.json deploy/server/

      - name: List files before zipping
        run: ls -R deploy

      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r release.zip .

      - name: List files after zipping
        run: ls -R deploy

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: deploy/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: List files for debug
        run: |
          ls -R

      - name: Unzip artifact for deployment
        run: unzip node-app/release.zip -d deploy

      - name: List files after unzipping
        run: ls -R deploy

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'planning-poker-100'
          slot-name: 'Production'
          package: deploy
